language: node_js
node_js:
  - "0.10"
script:
  - "grunt travis"
env:
  global:
    - secure: "ALGM5ytr4iQZOt0JduSVa+C/vpdOWVwRSaU6Uxwn3GIKnpUhxyRdCb7ELSUmI/i8RQMcnAR4sAlKedy9T4WXwjX6sEKnn6OY0bmqBulc1y21yu4S7EvHgu5h+4YpneXeQVVbzEn4TYPiZXI/wJgTPlW460XyZJrXyBa0OJy0C/4="
    - secure: "dmDllBuZ3xE0Wg0q+2QvcXCCaCakF1hHofaRb4EtEAmFDXf4KIBTYCuG1wO9HFm1Kh9lMdZZdB2Huk4bQOGar+KQQH+N8UyS61HlDFN1RjcJBTyUOaXo8t8h1nLvZNWwyWt6W/XxraPeUDYigigmAsC/ligxpVLrRsv6xR9rH44="
    - secure: "orvTJ3Q12AZ2k+aI2qYHmmfakzdG7wn7zS8109P/xczjEw44uUZe1/WMC327Wp7qYZqjDIZLYV/ViP1azm5PtwScPn8R54kx/Zv04HUstVGECprSCunYUdlRuAXirzYEC8n2gzIZEZOUB7ptyvIEkUB65qxX/qiq920ndY3hBYw="
    - secure: "HKzi6EBpXPYAKLz9qoIQLZrrSnpk0TTE2abzLYKy3yciIWVGNNBLT/9/+Nb94ITsax6sihpafPmKfZpeRzNLinhncnR/KZxQJ4htNKrpJzsJPVVuLy7M+To5ysEQ+yTGs0RsKf9efsI68X2C+jTvrUHJeX4IAPp7eeJKR15D5dc="
    - secure: "JtThIHmoWb4S2107+67ZV5Dzo/5qyDNmWy4nJFOD+39McBVKdxBmlg2TllrSjbUFb/taRr6e/maDRXyIyj/14F0FAT1wqqKeoKpoxGafu+IRQkfBVHWhjjXc2DgjLoMfBt5CyLHbX3u8nl6kuklj++C53OAN9LvLZexJK8b1eMQ="
    - secure: "N1Xf9bqZWbSqLP7co2jCppuWq2mzHWDsJ5eU4KA7KFpTL2IJpOkjsCxNtwSf882BJ9C4ALqvRRd4G8jOXC0dmMsZde9kY/5sUmT2mmEEUKljgxYjs3wbconwsC0+Bs2RM7Osd12+XusnNWMMNP9VT5IgoZn/yEY7xKZ/ya1Z7co="
